# Generated by Django 5.1.1 on 2024-09-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
    ]
