# Generated by Django 5.1.1 on 2024-09-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
